# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: main

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: remove dependencies
      run: mvn clean install 
    
    - name: install dependencies
      run: mvn  install 

    - name: build
      run: mvn install
      
  aws-autenticate: 
     needs: build
     runs-on: ubuntu-latest
     steps:
       - name: Amazon ECR "Login" Action for GitHub Actions
         run: echo "Autenticando com as crendicias da aws",
   
  deploy-docker-image: 
     runs-on: ubuntu-latest
     needs: aws-autenticate
     steps:
     - name: Deploy Docker to AWS (EC2)
       run: echo "Deploy to EC2"
 
